In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

from ISLP import load_data
from ISLP.models import summarize, ModelSpec, poly
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = load_data("Default")
df

     default student      balance        income
0         No      No   729.526495  44361.625074
1         No     Yes   817.180407  12106.134700
2         No      No  1073.549164  31767.138947
3         No      No   529.250605  35704.493935
4         No      No   785.655883  38463.495879
...      ...     ...          ...           ...
9995      No      No   711.555020  52992.378914
9996      No      No   757.962918  19660.721768
9997      No      No   845.411989  58636.156984
9998      No      No  1569.009053  36669.112365
9999      No     Yes   200.922183  16862.952321

[10000 rows x 4 columns]

In [3]:
df["default"] = pd.get_dummies(df["default"], drop_first=True)

In [4]:
df["default"] = df["default"].astype(int)
df

      default student      balance        income
0           0      No   729.526495  44361.625074
1           0     Yes   817.180407  12106.134700
2           0      No  1073.549164  31767.138947
3           0      No   529.250605  35704.493935
4           0      No   785.655883  38463.495879
...       ...     ...          ...           ...
9995        0      No   711.555020  52992.378914
9996        0      No   757.962918  19660.721768
9997        0      No   845.411989  58636.156984
9998        0      No  1569.009053  36669.112365
9999        0     Yes   200.922183  16862.952321

[10000 rows x 4 columns]

In [11]:
n = [0.2, 0.4, 0.8]
mean_res_comp = np.zeros(len(n))
for i in range(len(n)):
    df_Train, df_Test = train_test_split(df, test_size=n[i],random_state=0)
    
    X_train = df_Train[["balance", "income"]]
    Y_train = df_Train["default"]
    
    X_test = df_Test[["balance", "income"]]
    Y_test = df_Test["default"]
    
    lreg = LogisticRegression()
    lreg.fit(X_train, Y_train)
    
    y_pred = lreg.predict(X_test)
    mean_res_comp[i] = np.mean((Y_test - y_pred)**2)

    
    # y_pred = (lreg.predict_proba(X_test)[:,1] >= 0.7).astype(int)
    # to jest gdy chcemy sami ustalic od jakiego thresholdu klasyfikujemy
    # predict_proba zwraca nam zwykle prawdopodobienstwo
    # natomiast .predict() zwraca zwykle labelki {0,1}
    print(f"Results for test_size={n[i]}")
    print("Mean:", mean_res_comp[i])
    print("Acc:", accuracy_score(Y_test, y_pred))
    print(confusion_matrix(Y_test, y_pred))

Results for test_size=0.2
Mean: 0.028
Acc: 0.972
[[1921    5]
 [  51   23]]
Results for test_size=0.4
Mean: 0.028
Acc: 0.972
[[3838   13]
 [  99   50]]
Results for test_size=0.8
Mean: 0.027375
Acc: 0.972625
[[7699   26]
 [ 193   82]]

In [6]:
# d) col. student as a dummy var
df["student"] = pd.get_dummies(df["student"], drop_first=True)

df

      default  student      balance        income
0           0    False   729.526495  44361.625074
1           0     True   817.180407  12106.134700
2           0    False  1073.549164  31767.138947
3           0    False   529.250605  35704.493935
4           0    False   785.655883  38463.495879
...       ...      ...          ...           ...
9995        0    False   711.555020  52992.378914
9996        0    False   757.962918  19660.721768
9997        0    False   845.411989  58636.156984
9998        0    False  1569.009053  36669.112365
9999        0     True   200.922183  16862.952321

[10000 rows x 4 columns]

In [7]:
df["student"] = df["student"].astype(int)
df

      default  student      balance        income
0           0        0   729.526495  44361.625074
1           0        1   817.180407  12106.134700
2           0        0  1073.549164  31767.138947
3           0        0   529.250605  35704.493935
4           0        0   785.655883  38463.495879
...       ...      ...          ...           ...
9995        0        0   711.555020  52992.378914
9996        0        0   757.962918  19660.721768
9997        0        0   845.411989  58636.156984
9998        0        0  1569.009053  36669.112365
9999        0        1   200.922183  16862.952321

[10000 rows x 4 columns]

In [8]:
df_Train, df_Test = train_test_split(df, test_size=0.2,random_state=0)

Y_train = df_Train["default"]
X_train = df_Train.drop("default", axis=1)

Y_test = df_Train["default"]
X_test = df_Train.drop("default", axis=1)

X_test

lreg1 = LogisticRegression()

lreg1.fit(X_train, Y_train)

res = lreg1.predict(X_test)
mean_res = np.mean((Y_test - res)**2)
print(mean_res)
print(accuracy_score(Y_test, res))

difference = mean_res - min(mean_res_comp)
if (difference) < 0:
    print("MSE improved by: ", abs(difference))

0.02625
0.97375
MSE improved by:  0.001125000000000001